spring:
  security:
    oauth2:
      client:
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
        registration:
          github:
            client-id: Ov23lik6g6WygAhPnsUc
            client-secret: ecfcf33be7c7733bfdcd0e4671f01467ebf1a471
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code

app:
  jwt:
    expiration: 86400000 # 24 hours
  oauth2:
    redirectUri: http://localhost:3000/oauth2/redirect 